# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 6.0'

  target 'ImageFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageFinderUITests' do
    # Pods for testing
  end

end
